clear;

sin_table_128 = xlsread('sin_tables', 'sin_table_128');
sin_table_64 = xlsread('sin_tables', 'sin_table_64');

fs = 8000;

N = 128;
delta = 1.5;
n = 1:N;

frequency = delta/((1/fs)*N);

indexFracStep = fix( mod(delta.*n, N) )+1;

sigFracStep = sin_table_128( indexFracStep )./2^15;
sigFracStep = [0; sigFracStep(1:end-1)];    % alignment for matching ML sin
sigFracStepML = sin( 2*pi*frequency*(0:1/fs:(length(n)-1)/fs) )';   % reference signal generated via MATLAB
errorPureFracStep = sigFracStepML - sigFracStep;

figure
spectrogram(sigFracStep, 128, 64, 128, fs, 'yaxis');
colorbar('off');
title('Signal generated by the sin table');
figure
spectrogram(sigFracStepML, 128, 64, 128, fs, 'yaxis');
colorbar('off');
title('Signal generated by the built-in function');

figure
plot(sigFracStep);
title('Signal generated by the sin table');
hold on;
plot(sigFracStepML, '--m');
title('Signal generated by the built-in function');
plot(sigFracStep - sigFracStepML, 'r');
xlim([1 length(sigFracStep)]);
ylim([min(sigFracStep) max(sigFracStep)]);
legend('Signal generated by the sin table', 'Signal generated by the built-in function');
hold off;